<?php

namespace App\Request;

use Cake\Validation\Validator;

class MessageRequest extends FormRequest
{
    public function prepareData($data)
    {
        $numbers = explode(',',$data['to']);
        $this->prepareData = [
          'numbers' => $numbers
        ];

        return parent::prepareData($data); // TODO: Change the autogenerated stub
    }

    function rules(): void
    {
        $this->validator
            ->requirePresence('to', 'This field is required')
            ->notEmptyString('to', 'To is required')
            ->minLength('to', 6, 'Too short')
            ->notEmptyArray('numbers', 'Not number provided')
            ->requirePresence('message', 'This field is required')
            ->notEmptyString('message', 'Messate is required')
            ->maxLength('message', 255, 'Too long')
        ;
    }
}
